name: Build PDF

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:

jobs:

  pdflatex:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "CONDA_ENV_FILE=archive-specifications/environment.yml" >> $GITHUB_ENV
        echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV

    - name: Create conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        cache-downloads-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
        micromamba-version: 'latest'
        environment-file: archive-specifications/environment.yml
        extra-specs: |
          python=${{ matrix.python-version }}

    - name: Version info
      run: |
        conda info -a
        conda list

    - name: Create domain plots
      run: |
        python scripts/create-domain-plots.py markdown

    - name: Install latex dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y     \
          texlive-latex-recommended \
          texlive-latex-extra       \
          texlive-fonts-extra       \
          fonts-freefont-otf        \
          texlive-xetex             \
          latexmk                   \
          xindy
    - name: Build PDF from LaTeX (Docs)
      run: |
        jb build archive-specifications --builder pdflatex -n --keep-going
    - uses: actions/upload-artifact@v3
      with:
        name: PDF_LATEX
        path: archive-specifications/_build/latex/book.pdf
